% This is a MATLAB script demonstrating compiling kinetic model files
%
% OpenKMAP Oct 2024.

%% Compilatoin (without OMP)
%
% Collect the files of different kinetic models
kmodFiles = {'ktac_1tcm_mex', 'kfit_1tcm_mex', ...
             'ktac_2tcm_mex', 'kfit_2tcm_mex', ...
             'ktac_liver_mex', 'kfit_liver_mex'};

% Compile each file
for i = 1:length(kmodFiles)
    i
    file_i = sprintf('%s.cpp',kmodFiles{i})
    mex(file_i, ...
    '../src/kmaplib_common.cpp',...
    '../src/kmaplib_infun.cpp',...
    '../src/kmaplib_models.cpp',...
    '../src/kmaplib_optimization.cpp',...
    '-I../src/'); 
end

%% Compilatoin for files with OMP
%
% % Collect the files of different kinetic models that are with omp
% kmodFiles = {'kfit_1tcm_mex_omp', ...
%              'kfit_2tcm_mex_omp', ...
%              'kfit_liver_mex_omp'};
% 
% % Compile each file
% for i = 1:length(kmodFiles)
%     file_i = sprintf('%s.cpp',kmodFiles{i})
%     mex('-v', file_i, ...
%     '../src/kmaplib_common.cpp',...
%     '../src/kmaplib_infun.cpp',...
%     '../src/kmaplib_models.cpp',...
%     '../src/kmaplib_optimization.cpp',...
%     '-I../src/',...
%     'CXXFLAGS="$CXXFLAGS -fopenmp"', ...
%     'LDFLAGS="$LDFLAGS -fopenmp"');
% end
