mex -v ../mex/kfit_srtm_mex.cpp ...
    ../src/kmaplib_common.cpp ...
    ../src/kmaplib_infun.cpp ...
    ../src/kmaplib_models.cpp ...
    ../src/kmaplib_optimization.cpp ...
    -I../src/ ...
    CXXFLAGS='$CXXFLAGS -fopenmp' ...
    LDFLAGS='$LDFLAGS -fopenmp'