mex -v ../mex/kfit_2tcm_mex_omp.cpp ...
    ../src/kmaplib_common.cpp ...
    ../src/kmaplib_infun.cpp ...
    ../src/kmaplib_models.cpp ...
    ../src/kmaplib_optimization.cpp ...
    -I../src/ ...
    CXXFLAGS='$CXXFLAGS -fopenmp' ...
    LDFLAGS='$LDFLAGS -fopenmp'